spring:
  application:
    name: parser
  datasource:
    url: jdbc:postgresql://localhost:5432/logdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
  elasticsearch:
    uris: http://localhost:9200
  jackson:
    time-zone: UTC
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: log-consumer-group
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      batch-listener: true
#      common-error-handler: true
#      max-poll-records: 50

file:
  upload-dir: parser/src/main/resources/uploads
  secret: secret.yaml

server:
  port: 8081

log:
  format:
    java:
      spring-boot: '^(?<timestamp>\S+)\s+(?<level>\w+)\s+(?<pid>\d+)\s+---\s+\[(?<context>.*?)\]\s+\[(?<thread>.*?)\]\s+(?<className>\S+)\s+:\s+(?<message>.*)$'
      log4j: '^(?<timestamp>\d{4}-\d{2}-\d{2}[\sT]\d{2}:\d{2}:\d{2}[,\.]\d+)\s+\[(?<thread>.*?)\]\s+(?<level>\w+)\s+(?<className>[\w\.$]+)\s+-\s+(?<message>.*)$'
      simple-java: '^(?<timestamp>\w+\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}:\d{2}\s+[AP]M)\s+(?<className>[\w\.]+)\s+(?<method>\w+)\n(?<level>\w+):\s+(?<message>.*)$'
