spring:
  application:
    name: parser
  datasource:
    url: jdbc:postgresql://localhost:5432/logdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
  jackson:
    time-zone: UTC
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: log-consumer-group
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      batch-listener: true
#      common-error-handler: true
#      max-poll-records: 50

file:
  upload-dir: ingestion/src/main/resources/uploads

server:
  port: 8081

log:
  format:
    java:
#      2026-05-02T23:49:08.092+05:30  INFO 15740 --- [parser] [           main] c.logAnalyzer.parser.ParserApplication   : No active profile set, falling back to 1 default profile: "default"
      spring-boot: '^(?<timestamp>\S+)\s+(?<level>\w+)\s+(?<pid>\d+)\s+---\s+\[(?<context>.*?)\]\s+\[(?<thread>.*?)\]\s+(?<className>\S+)\s+:\s+(?<message>.*)$'
#      Apr 26, 2026 7:07:33 PM com.app.Service main
#      INFO: Something happened
      simple-java: '^(?<timestamp>\w+\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}:\d{2}\s+[AP]M)\s+(?<className>[\w\.]+)\s+(?<method>\w+)\n(?<level>INFO|WARNING|SEVERE):\s+(?<message>.*)$'
#      2026-04-26 19:07:33,316 INFO [main] com.app.Service - Application started
      log4j: '^(?<timestamp>\d{4}-\d{2}-\d{2}[\sT]\d{2}:\d{2}:\d{2}[,\.]\d+)\s+(?<level>INFO|ERROR|WARN|DEBUG|TRACE)\s+\[(?<thread>.*?)\]\s+(?<class>[\w\.$]+)\s+-\s+(?<message>.*)$'
#      at com.app.Service.method(Service.java:45)
      stack-trace-line: '^\s*at\s+(?<class>[\w\.]+)\.(?<method>\w+)\((?<file>.*?):(?<line>\d+)\)$'
#      java.lang.NullPointerException: Something went wrong
      exception: '^(?<exception>[\w\.]+):\s+(?<message>.*)$'
